[package]
name = "eval_data_generator"
version = "0.1.0"
authors = ["Tim <tim.tannert@tu-dortmund.de>"]
edition = "2018"

[dependencies]
serde = "1.0.99"
rmp-serde = "0.13.7"
rand = "0.7.0"
rand_pcg = "0.2.0"
uint = { path = "../uint" }