[package]
name = "space_measure"
version = "0.1.0"
authors = ["Tim <tim.tannert@tu-dortmund.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stats_alloc = "0.1.8"
stree = { path = "../Implementierung/" }
uint = { git = "https://github.com/Tockra/uint.git" }
serde = "1.0.99"
rmp-serde = "0.13.7"